### PR TITLE
fix(cardano-chain-follower): Refactor cardano-chain-follower to fix client concurrency bug

### LINKED ISSUE #180: [Bug]: Cardano chain follower fails to set read pointer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Follower fails if a set read pointer request is received when it's waiting for a response from the node.

NOTE: seems that pallas client can't be used concurrently.

### Expected Behavior

Follower should cancel the current request (or wait for it to be complete) and handle the set pointer request correctly.

### Project

Backend

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FelipeRosa**
# Description

This PR fixes a bug that caused the `Follower` to get stuck when trying to set its read pointer while waiting for the next chain update.

## Related Issue(s)

Closes #180 

### Background task

- `Follower` background task refactored to allow dropping the client and recreating it when setting the read pointer (which is needed because there seems to be no way of aborting an ongoing request to the node)
- Removed "read requests" from the follow task so the follow task is now only responsible for fetching chain updates and setting the read pointer when requested

### read_block and read_block_range
`Follower::read_block` and `Follower::read_block_range` now spawn futures and return join handles to make it possible to make read requests concurrently while not depending on the follower's background task.

### New examples

- Added `set_read_pointer` example that shows changing the follower's read pointer while following the chain
- Added `concurrent_reads` example that shows how to read chain blocks concurrently

## Breaking Changes

- Some variants of the crate's `Error` type were renamed/removed 
- `ReadBlock` and `ReadBlockRange` implement `Future` and should be awaited directly, i.e.: `follower.read_block().await` instead of `follower.read_block().read().await`

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs [hunk 1]
```diff
@@ -0,0 +1,74 @@
+//! This example shows how set the follower's read pointer without stopping it.
```
Comment (bkioshn) [inline hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs:1]: typo "how to"

File: hermes/crates/cardano-chain-follower/src/follow.rs [hunk 2]
```diff
@@ -328,565 +380,386 @@ impl Follower {
...
-    async fn handle_request(state: TaskState, request: Request) {
-        match request {
-            Request::SetReadPointer { at, response_tx } => {
-                handle_set_read_pointer_request(at, state, response_tx).await;
-            },
-            Request::ReadBlock {
-                at,
+        /// Runs the follow task.
+        ///
+        /// It keeps asking the connected node new chain updates. Every update and
```
Comment (bkioshn) [inline hermes/crates/cardano-chain-follower/src/follow.rs:464]: "for new chain ...."

**Review by bkioshn — COMMENTED** [review]
Looks good to me. Quite clear after taking a look at the code after the last tech discussion. Just a few grammar error (:

File: hermes/crates/cardano-chain-follower/src/follow.rs (hunk 2 above)
Comment (stevenj) [inline hermes/crates/cardano-chain-follower/src/follow.rs:464]:
```suggestion
        /// It keeps asking the connected node for new chain updates. Every update and
```

File: hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs (hunk 1 above)
Comment (stevenj) [inline hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs:1]:
```suggestion
//! This example shows how to set the follower's read pointer without stopping it.
```

**Review by stevenj — APPROVED** [review]
LGTM, added suggestions for the grammar issues @bkioshn already mentioned.

**Review by stevenj — APPROVED** [review]
LGTM
